// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server.proto

#include "server.pb.h"
#include "server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fileserver {
namespace v1 {

static const char* FileService_method_names[] = {
  "/fileserver.v1.FileService/InitUpload",
  "/fileserver.v1.FileService/CompleteUpload",
  "/fileserver.v1.FileService/GetDownloadUrl",
};

std::unique_ptr< FileService::Stub> FileService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileService::Stub> stub(new FileService::Stub(channel, options));
  return stub;
}

FileService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_InitUpload_(FileService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CompleteUpload_(FileService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDownloadUrl_(FileService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FileService::Stub::InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::fileserver::v1::InitUploadRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InitUpload_, context, request, response);
}

void FileService::Stub::async::InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitUpload_, context, request, response, std::move(f));
}

void FileService::Stub::async::InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitUpload_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>* FileService::Stub::PrepareAsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileserver::v1::InitUploadRsp, ::fileserver::v1::InitUploadReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InitUpload_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>* FileService::Stub::AsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitUploadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::fileserver::v1::CompleteUploadRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CompleteUpload_, context, request, response);
}

void FileService::Stub::async::CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteUpload_, context, request, response, std::move(f));
}

void FileService::Stub::async::CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CompleteUpload_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>* FileService::Stub::PrepareAsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileserver::v1::CompleteUploadRsp, ::fileserver::v1::CompleteUploadReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CompleteUpload_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>* FileService::Stub::AsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCompleteUploadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::fileserver::v1::GetDownloadUrlRsp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDownloadUrl_, context, request, response);
}

void FileService::Stub::async::GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDownloadUrl_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDownloadUrl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>* FileService::Stub::PrepareAsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileserver::v1::GetDownloadUrlRsp, ::fileserver::v1::GetDownloadUrlReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDownloadUrl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>* FileService::Stub::AsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDownloadUrlRaw(context, request, cq);
  result->StartCall();
  return result;
}

FileService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileserver::v1::InitUploadReq* req,
             ::fileserver::v1::InitUploadRsp* resp) {
               return service->InitUpload(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileserver::v1::CompleteUploadReq* req,
             ::fileserver::v1::CompleteUploadRsp* resp) {
               return service->CompleteUpload(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileserver::v1::GetDownloadUrlReq* req,
             ::fileserver::v1::GetDownloadUrlRsp* resp) {
               return service->GetDownloadUrl(ctx, req, resp);
             }, this)));
}

FileService::Service::~Service() {
}

::grpc::Status FileService::Service::InitUpload(::grpc::ServerContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::CompleteUpload(::grpc::ServerContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetDownloadUrl(::grpc::ServerContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fileserver
}  // namespace v1
#include <grpcpp/ports_undef.inc>

