// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server.proto
#ifndef GRPC_server_2eproto__INCLUDED
#define GRPC_server_2eproto__INCLUDED

#include "server.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace fileserver {
namespace v1 {

class FileService final {
 public:
  static constexpr char const* service_full_name() {
    return "fileserver.v1.FileService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 初始化上传，获得 MinIO 预签名上传 URL
    virtual ::grpc::Status InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::fileserver::v1::InitUploadRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>> AsyncInitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>>(AsyncInitUploadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>> PrepareAsyncInitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>>(PrepareAsyncInitUploadRaw(context, request, cq));
    }
    // 客户端上传完成后，通知 FileServer 检查文件
    virtual ::grpc::Status CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::fileserver::v1::CompleteUploadRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>> AsyncCompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>>(AsyncCompleteUploadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>> PrepareAsyncCompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>>(PrepareAsyncCompleteUploadRaw(context, request, cq));
    }
    // 获取短期有效的下载 URL
    virtual ::grpc::Status GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::fileserver::v1::GetDownloadUrlRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>> AsyncGetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>>(AsyncGetDownloadUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>> PrepareAsyncGetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>>(PrepareAsyncGetDownloadUrlRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 初始化上传，获得 MinIO 预签名上传 URL
      virtual void InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 客户端上传完成后，通知 FileServer 检查文件
      virtual void CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取短期有效的下载 URL
      virtual void GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>* AsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::InitUploadRsp>* PrepareAsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>* AsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::CompleteUploadRsp>* PrepareAsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>* AsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fileserver::v1::GetDownloadUrlRsp>* PrepareAsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::fileserver::v1::InitUploadRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>> AsyncInitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>>(AsyncInitUploadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>> PrepareAsyncInitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>>(PrepareAsyncInitUploadRaw(context, request, cq));
    }
    ::grpc::Status CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::fileserver::v1::CompleteUploadRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>> AsyncCompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>>(AsyncCompleteUploadRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>> PrepareAsyncCompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>>(PrepareAsyncCompleteUploadRaw(context, request, cq));
    }
    ::grpc::Status GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::fileserver::v1::GetDownloadUrlRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>> AsyncGetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>>(AsyncGetDownloadUrlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>> PrepareAsyncGetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>>(PrepareAsyncGetDownloadUrlRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, std::function<void(::grpc::Status)>) override;
      void InitUpload(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, std::function<void(::grpc::Status)>) override;
      void CompleteUpload(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, std::function<void(::grpc::Status)>) override;
      void GetDownloadUrl(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>* AsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::InitUploadRsp>* PrepareAsyncInitUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::InitUploadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>* AsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::CompleteUploadRsp>* PrepareAsyncCompleteUploadRaw(::grpc::ClientContext* context, const ::fileserver::v1::CompleteUploadReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>* AsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fileserver::v1::GetDownloadUrlRsp>* PrepareAsyncGetDownloadUrlRaw(::grpc::ClientContext* context, const ::fileserver::v1::GetDownloadUrlReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_InitUpload_;
    const ::grpc::internal::RpcMethod rpcmethod_CompleteUpload_;
    const ::grpc::internal::RpcMethod rpcmethod_GetDownloadUrl_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 初始化上传，获得 MinIO 预签名上传 URL
    virtual ::grpc::Status InitUpload(::grpc::ServerContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response);
    // 客户端上传完成后，通知 FileServer 检查文件
    virtual ::grpc::Status CompleteUpload(::grpc::ServerContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response);
    // 获取短期有效的下载 URL
    virtual ::grpc::Status GetDownloadUrl(::grpc::ServerContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InitUpload() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitUpload(::grpc::ServerContext* context, ::fileserver::v1::InitUploadReq* request, ::grpc::ServerAsyncResponseWriter< ::fileserver::v1::InitUploadRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompleteUpload(::grpc::ServerContext* context, ::fileserver::v1::CompleteUploadReq* request, ::grpc::ServerAsyncResponseWriter< ::fileserver::v1::CompleteUploadRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDownloadUrl(::grpc::ServerContext* context, ::fileserver::v1::GetDownloadUrlReq* request, ::grpc::ServerAsyncResponseWriter< ::fileserver::v1::GetDownloadUrlRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_InitUpload<WithAsyncMethod_CompleteUpload<WithAsyncMethod_GetDownloadUrl<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InitUpload() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fileserver::v1::InitUploadReq* request, ::fileserver::v1::InitUploadRsp* response) { return this->InitUpload(context, request, response); }));}
    void SetMessageAllocatorFor_InitUpload(
        ::grpc::MessageAllocator< ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitUpload(
      ::grpc::CallbackServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fileserver::v1::CompleteUploadReq* request, ::fileserver::v1::CompleteUploadRsp* response) { return this->CompleteUpload(context, request, response); }));}
    void SetMessageAllocatorFor_CompleteUpload(
        ::grpc::MessageAllocator< ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CompleteUpload(
      ::grpc::CallbackServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fileserver::v1::GetDownloadUrlReq* request, ::fileserver::v1::GetDownloadUrlRsp* response) { return this->GetDownloadUrl(context, request, response); }));}
    void SetMessageAllocatorFor_GetDownloadUrl(
        ::grpc::MessageAllocator< ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDownloadUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_InitUpload<WithCallbackMethod_CompleteUpload<WithCallbackMethod_GetDownloadUrl<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InitUpload() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InitUpload() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInitUpload(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCompleteUpload(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDownloadUrl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InitUpload() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InitUpload(context, request, response); }));
    }
    ~WithRawCallbackMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InitUpload(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CompleteUpload(context, request, response); }));
    }
    ~WithRawCallbackMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CompleteUpload(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDownloadUrl(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDownloadUrl(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InitUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InitUpload() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fileserver::v1::InitUploadReq, ::fileserver::v1::InitUploadRsp>* streamer) {
                       return this->StreamedInitUpload(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InitUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InitUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::InitUploadReq* /*request*/, ::fileserver::v1::InitUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInitUpload(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fileserver::v1::InitUploadReq,::fileserver::v1::InitUploadRsp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CompleteUpload : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CompleteUpload() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fileserver::v1::CompleteUploadReq, ::fileserver::v1::CompleteUploadRsp>* streamer) {
                       return this->StreamedCompleteUpload(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CompleteUpload() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CompleteUpload(::grpc::ServerContext* /*context*/, const ::fileserver::v1::CompleteUploadReq* /*request*/, ::fileserver::v1::CompleteUploadRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCompleteUpload(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fileserver::v1::CompleteUploadReq,::fileserver::v1::CompleteUploadRsp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDownloadUrl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDownloadUrl() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fileserver::v1::GetDownloadUrlReq, ::fileserver::v1::GetDownloadUrlRsp>* streamer) {
                       return this->StreamedGetDownloadUrl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDownloadUrl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDownloadUrl(::grpc::ServerContext* /*context*/, const ::fileserver::v1::GetDownloadUrlReq* /*request*/, ::fileserver::v1::GetDownloadUrlRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDownloadUrl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fileserver::v1::GetDownloadUrlReq,::fileserver::v1::GetDownloadUrlRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_InitUpload<WithStreamedUnaryMethod_CompleteUpload<WithStreamedUnaryMethod_GetDownloadUrl<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_InitUpload<WithStreamedUnaryMethod_CompleteUpload<WithStreamedUnaryMethod_GetDownloadUrl<Service > > > StreamedService;
};

}  // namespace v1
}  // namespace fileserver


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_server_2eproto__INCLUDED
